[package]
name = "pinyincd"
version = "0.1.0"
authors = ["kkew3"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinyin = "0.9.0"
home = "0.5.3"